"""empty message

Revision ID: 4e0f1d3d5597
Revises: 
Create Date: 2023-06-07 15:28:22.975757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e0f1d3d5597'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(length=2000), nullable=False),
    sa.Column('short_url', sa.String(length=8), nullable=False),
    sa.Column('custom_url', sa.String(length=20), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('qr_code', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_url'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    # ### end Alembic commands ###
