"""empty message

Revision ID: 6542a1c7c6ad
Revises: 4e0f1d3d5597
Create Date: 2023-06-07 16:07:12.373286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6542a1c7c6ad'
down_revision = '4e0f1d3d5597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('short_url',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=6),
               existing_nullable=False)
        batch_op.alter_column('custom_url',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('qr_code',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('clicks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicks', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('qr_code',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)
        batch_op.alter_column('custom_url',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('short_url',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('user_id')
        batch_op.drop_column('created_at')

    op.drop_table('click')
    # ### end Alembic commands ###
