"""empty message

Revision ID: d0e7fcf7ad45
Revises: 
Create Date: 2023-06-16 01:17:49.898182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e7fcf7ad45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clicks', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_column('clicks')

    # ### end Alembic commands ###
